kbknapp/cargo-outdated

Cargo.lock, Cargo.toml
I consider Using `*` to be a bad practice since it 'skips' SemVer and only works based on pure luck :)
(There's even a [RFC](https://github.com/rust-lang/rfcs/pull/1241) to not allow `*` for crates.io crates.)
=> Dependencies: Use Version Numbers Instead of '*'

src/lockfile.rs
This makes cargo-outdated work (better?) on Windows. Previously, it failed with a "permission denied" error for me, which was presumably caused by the files not being deleted immediately by Windows.
Since `File::create` truncates existing files, the behavior should be the same as before.
=> Truncate temporary files instead of deleting, then recreating them

src/lockfile.rs
This makes the output much more easy to parse, consistent between runs and also groups transitive dependencies by the original dependency.
By the way, `Cargo.lock` should probably be updated, it still lists version `0.1.2` for `cargo-outdated` (which cargo will update when you do a `cargo build`).
=> imp: sort output

src/deps/dep.rs, src/lockfile.rs
Traverse all dependencies when building the dependency tree, and don't prune non-registry dependencies until the final step.  This fixes the output for projects like servo that are split into several crates in a single repo, with path dependencies between them.
=> Include children of non-registry dependencies

Cargo.toml
with Link Time Optimization, `cargo-outdated`'s binary size can reduce about 3% (on my Linux)
=> chore: use LTO (Link Time Optimization)

src/deps/raw_dep.rs, src/lockfile.rs, src/main.rs
This fixes a bug where some indirect dependencies were not processed, because they were added to the `deps` map with a name like `foo->bar`, so they weren't found when a later pass checked for just `bar`.
=> Fix recursion through indirect dependencies

src/config.rs, src/lockfile.rs, src/main.rs
This can be useful in a workspace, especially one with a [virtual manifest][1].
[1]: https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md#virtual-cargotoml
=> Allow overriding the root package

README.md, src/cargo_ops/elaborate_workspace.rs
This makes the output look a little bit nicer:
```
$ cargo outdated
Name                    Project  Compat  Latest  Kind    Platform
parking_lot_core->libc  0.2.30   0.2.31  0.2.31  Normal  cfg(unix)
rand->libc              0.2.30   0.2.31  0.2.31  Normal  ---
rbpf->libc              0.2.30   0.2.31  0.2.31  Normal  ---
time->libc              0.2.30   0.2.31  0.2.31  Normal  ---
$ cargo outdated
Name                    Project  Compat  Latest  Kind    Platform
----                    -------  ------  ------  ----    --------
parking_lot_core->libc  0.2.30   0.2.31  0.2.31  Normal  cfg(unix)
rand->libc              0.2.30   0.2.31  0.2.31  Normal  ---
rbpf->libc              0.2.30   0.2.31  0.2.31  Normal  ---
time->libc              0.2.30   0.2.31  0.2.31  Normal  ---
```
=> style(elaborate_workspace): Underline headers.

README.md
It seems that many users are still confused by the `Latest` column so here's a brief explanation.
`cargo-outdated` currently is actually not aware of the real latest transitive dependencies, which tends to be somewhat meaningless to most users.
=> docs: briefly explains how `cargo-outdated` works

src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/main.rs
Closes #58. Rebasing and squeezing needed before merging.
Example 1:
```
⇒  cargo run -- outdated -m ~/Programming/Rust/Rocket/Cargo.toml
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running `target/debug/cargo-outdated outdated -m /home/frederick/Programming/Rust/Rocket/Cargo.toml`
rocket
================
Name               Project     Compat  Latest   Kind    Platform
----               -------     ------  ------   ----    --------
base64             0.6.0       ---     0.7.0    Normal  ---
hyper              0.10.13     ---     0.11.2   Normal  ---
hyper-sync-rustls  0.3.0-rc.1  ---     0.2.1    Normal  ---
idna               0.1.4       ---     Removed  Normal  ---
libc               0.2.31      ---     Removed  Normal  ---
log                0.3.8       --- …
```
=> feat: loop through workspace members

README.md, src/cargo_ops/elaborate_workspace.rs, src/main.rs
Fixes #81 
And since the root package is actually a workspace member itself, running `cargo outdated` with or without `-w` gives the same output if cargo workspace feature is not enabled.
Finger crossed that there are no side effects.
=> imp: provide `--workspace` flag to enforce workspace mode

README.md, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/mod.rs, src/cargo_ops/temp_project.rs, src/main.rs
Fixes #84
Fixes #75
Rebase before merge
=> imp: queries crates.io api for new versions and feature changes

src/cargo_ops/elaborate_workspace.rs, src/main.rs
Fixes #105 
There was a bug in the old algorithm: `(grand, parent, self)` should not be used as the identifier of a package in the dependency tree.
The dependency tree comparison part has been rewritten to fix it and adopt BFS instead of DFS. No idea why I wrote a verbose DFS...
=> fix: rewrite dependency tree comparison algorithm

Cargo.lock
Lock file is currently broken; this fixes it.
```
$ git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ cargo build --frozen
error: the lock file /home/ben/Dev/third-party/cargo-outdated/Cargo.lock needs to be updated but --frozen was passed to prevent this
```
```
$ git co fix-lock-file 
Switched to branch 'fix-lock-file'
Your branch is up to date with 'ben/fix-lock-file'.
$ cargo build --frozen
Finished dev [unoptimized + debuginfo] target(s) in 0.17s
```
=> chore: fix lock file

src/cargo_ops/temp_project.rs
This is a minor patch, but with a project of mine I still experience an error (version conflict) so I'm not certain if it really fixes the issue yet. I'll have to investigate that further.
=> Implement support for now stable rename_dependency feature. Fixes #133.

src/cargo_ops/temp_project.rs
Minor change, that didn't make it into the last PR (using panic for this is not so nice but cargo fails before this is reached anyway, this commit is just to remove the TODO from my last commit):
https://github.com/kbknapp/cargo-outdated/pull/161#discussion_r253272795
=> Emit an error, when package key is not a string.

src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs
Some edge cases (e.g. vendored content) make cargo fail.
It's still useful for cargo-outdated to return a result in this case. This catches failures of expansion and makes them warnings rather than failure cases.
This makes cargo-outdated's output partial, but still useful
=> Makes cargo-outdated more resilient to edge cases in finding dependencies

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/main.rs
```
% cargo update
Updating crates.io index
Updating aho-corasick v0.7.3 -> v0.7.4
Updating backtrace v0.3.30 -> v0.3.32
Updating backtrace-sys v0.1.28 -> v0.1.30
Updating bitflags v1.0.4 -> v1.1.0
Updating bstr v0.1.4 -> v0.2.1
Removing build_const v0.2.1
Updating byteorder v1.3.1 -> v1.3.2
Adding c2-chacha v0.2.2
Removing crc v1.8.1
Updating curl-sys v0.4.18 -> v0.4.20
Updating env_logger v0.6.1 -> v0.6.2
Updating flate2 v1.0.7 -> v1.0.9
Adding getrandom v0.1.6
Updating globset v0.4.3 -> v0.4.4
Updating jobserver v0.1.13 -> v0.1.14
Updating miniz_oxide v0.2.1 -> v0.2.2
Updating miniz_oxide_c_api v0.2.1 -> v0.2.2
Updating num_cpus v1.10.0 -> v1.10.1
Adding ppv-lite86 v0.2.5
Adding rand v0.7.0
Adding rand_chacha v0.2.0
Adding rand_core v0.5.0
Adding rand_hc v0.2.0
Updating redox_syscall …
```
=> chore: Bump old dependencies

Cargo.toml
Fixes https://github.com/kbknapp/cargo-outdated/issues/173
=> Bump cargo to 0.38

Cargo.toml, src/cargo_ops/temp_project.rs
Fixes #175 the temp crate needs to check for the presence of `default-run` and then recreate the default-run option when copying to the temp directory in order to build the temporary crate to grab the dependencies. 
This is a WIP because the path code is a bit nasty and good enough to prove that this works for tonight...I'm tired :/
=> Fix `default-run` Issue

Cargo.toml, src/cargo_ops/temp_project.rs
This using the already included `semver` crate to parse the channels (`alpha`, `beta`, etc.) rather than string splits and slices. 
Resolves the panic in #168 because the parsing wasn't fully pulling the "alpha" to compare it to the latest release (which was parsed with `semver`). 
This PR **doesn't** solve the fact that it is **not** comparing the latest pre-release channel and will report that `0.2.0-alpha.2` is up-to-date with `0.2.0-alpha.2a` for a specific example. 
I will put in a seperate PR for that fix which I need to start looking into shortly.....
=> Changed the version parsing in temp_project.rs:valid_latest_version()

src/cargo_ops/temp_project.rs
Resolves #183 by copying in the `.cargo/config` file to the temporary working directory if it exists in the root.
=> Fixing .cargo/config options

Cargo.lock, Cargo.toml, src/cargo_ops/temp_project.rs
Before were were not checking if the `links` or `build` values were set it the `packages` section of the `Cargo.toml` this addition solves #189 under my replication by checking if those values are in the manifest and then copying the build file over to the temporary workspace. 
I do not use these features very often though, so please let me know if there are any edge cases that would be left out!
=> Fixing Build File to Temporary Workspace 

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs
This helps resolve #191 I was having trouble with it for a while still not resolving, but ironically we are having some network issues at the office, please help test this branch! 
I also noticed that the `CargoHttpConfig` struct is a [cached struct](https://docs.rs/cargo/0.41.0/src/cargo/util/config/mod.rs.html#97) so I had to remove the `Cargo.lock` to get it to cooperate in some rare cases.
=> Bumped and fixed the API updates for cargo v0.40.0 -> v0.42.0

src/main.rs
This allows using relative path for `--manifest-path`, such as in:
```
cargo outdated --manifest-path Cargo.toml
```
This makes it consistent with other cargo commands.
=> Allow relative manifest path

Cargo.lock, Cargo.toml
#195 that does not correctly parse ssh urls within the Cargo.toml this
is a fix that can be updated once Cargo v0.43.0 is release via @ehuss
=> This locks the url version to 2.1.0 instead of 2.1.1 which solves issue

README.md
In my previous PR that allows relative manifest path, I forgot changing the output example of `--help` in README.md.
=> fix help text of --manifest-path in README.md

Cargo.lock, Cargo.toml, src/cargo_ops/temp_project.rs, src/main.rs
This PR enables `$CARGO_HOME` when building the temp projects with `cargo-outdated`. This alleviates the need for re-downloading dependencies each time `cargo-outdated` is ran. 
Tested on MacOS, Ubuntu locally. Partially(?) resolves #211
=> Add `$CARGO_HOME` to `cargo` build path

Cargo.lock, Cargo.toml, src/cargo_ops/temp_project.rs
Updated the code from issue #219 and added comments explaining what
why it is necessary to not crawl the CARGO_HOME for Cargo.toml files.
=> Removed the always matching blank string for the CARGO_HOME variable.

README.md, src/cargo_ops/elaborate_workspace.rs, src/main.rs
This is particularly useful when used together with `--exit-code 1`.
Given a situation like this:
```
$ cargo outdated
Name             Project  Compat  Latest   Kind         Platform
----             -------  ------  ------   ----         --------
clap             2.20.0   2.20.5  2.26.0   Normal       ---
clap->bitflags   0.7.0    ---     0.9.1    Normal       ---
clap->libc       0.2.18   0.2.29  Removed  Normal       ---
clap->term_size  0.2.1    0.2.3   0.3.0    Normal       ---
clap->vec_map    0.6.0    ---     0.8.0    Normal       ---
num_cpus         1.6.0    ---     1.6.2    Development  ---
num_cpus->libc   0.2.18   0.2.29  0.2.29   Normal       ---
pkg-config       0.3.8    0.3.9   0.3.9    Build        ---
term             0.4.5    ---     0.4.6    Normal       --- …
```
=> Option for ignoring certain outdated dependencies

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/main.rs
Updating Cargo to `0.45.1`, plus updated `temp_project.rs` to not panic on [`find_update()`](https://github.com/deg4uss3r/cargo-outdated/blob/main/src/cargo_ops/temp_project.rs#L377) when the version cannot be compared but rather emit a warning with the `Cargo.toml` file and `crates.io` versions differ. 
Closes #225
=> Update Cargo and Fix Crash when Checking `semver` of crates 

src/cargo_ops/temp_project.rs
Use `Path::starts_with` to compare paths, which will only compare whole
path components, otherwise "/foo/bar-test/test" is a recognized as
a subdirectory of "/foo/bar".
=> fix(temp_project::manifest_paths): fix subpath check

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs
Moved from `serde_json::to_writer` to `serde_json::to_string` and `println!` (vice accessing by `io::stdout()`), also updated the data structure of dependencies from a `HashSet` to a `BTreeSet` with the ordering dependent on the crate name for more consistent output at the expense of a slight performance hit.
Resolves #241
=> Fix #241 JSON output formatting

.github/workflows/rust.yml
Enables checks for [stable, beta, nightly] on [ubuntu, macOS, and Windows] using Github CI.
=> enabling Github CI

Cargo.toml, README.md
Allows cargo-outdated to be built on MacOS without the need for a new version of OpenSSL (usually installed via homebrew)
=> Add feature to build cargo with vendored openssl

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs
Would close https://github.com/kbknapp/cargo-outdated/issues/258.
=> Bump cargo from 0.50 to 0.52

src/cargo_ops/temp_project.rs
Fixes the error where you cannot find a version for a specific crate by carrying workspace mode to the temp project
resolves #260 #230 #132
=> Carry Workspace Over

src/cargo_ops/mod.rs
A project using 2021 edition has `cargo-features = ["edition2021"]` in its Cargo.toml but cargo-outdated ignores it when serialization/deserialization and fails to parse the compat workspace. By adding this cargo-outdated can work with projects with 2021 edition.
=> Add the missing `cargo-features` entry in `Manifest`.

README.md
=> README: Add packaging status for cargo-outdated

src/cargo_ops/temp_project.rs, src/main.rs
It seems that `TempProject::find_updates` calls `SourceId::load` to get a registry for queries, but that function doesn't pay attention to registry overrides in the config. `SourceConfigMap::load` *does* take them into account, and everything else seems to work fine once the override is correctly configured.
I tested this by adding `127.0.0.1     localhost` to `/etc/hosts` to prevent cargo from accessing the servers. ~~I intend to add a more thorough test for CI here but wanted to make sure this seems like the right fix to maintainers beforehand.~~ It looks like CI isn't running much in the way of tests so I'm hesitant to build out a whole harness just for this, let me know what your preference is.
EDIT: For context, the motivation here is to allow isolated CI testing of a crate update …
=> Support checking for offline updates against a local registry

.github/workflows/ci-pr.yml, .github/workflows/ci.yml, Cargo.lock, src/cargo_ops/temp_project.rs
Fixes #291.
`Source::query_vec()` requires that the `Config` package lock is held or it panics. The way this works is strange, however. The lock itself is a filesystem lock - it creates the file `.cargo/.package-cache`. `acquire_package_cache_lock()` says that it can be acquired recursively:
>Acquires an exclusive lock on the global "package cache"
>
>This lock is global per-process and can be acquired recursively. An RAII structure is returned to release the lock, and if this abnormally terminates the lock is also released.
However, the way this is implemented is that each `Config` has its own `package_cache_lock`. If you try to acquire locks on two different `Config`s it deadlocks. So I removed the two `self.config` locks and moved it all into a larger scope that holds a lock on the …
=> Fix acquiring package cache lock for SourceConfigMap

src/main.rs
In prep for switching out the CLI parser, we need to ensure users won't need to change any existing CI/scripts/etc.
=> tests: adds CLI UX tests

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/cli.rs, src/main.rs
Re-introduces `clap` as a dependency and removes `docopt`.
There are a few motivating factors:
- When `cargo-outdated` was originally created, it used `clap`
- When `cargo` became a dependency of `cargo-oudated` the CLI parser was
changed to `docopt` because that's what `cargo` used.
- Since that time, `cargo` has changed it's CLI parser to `clap`
- [`docopt` has been effectively unmaintained for  years](https://github.com/clap-rs/clap/issues/2951#issuecomment-952882684), which is also noted in their README
This commit shaves ~31 seconds off the compile time on my CPU (Intel i9-9980HK). I
haven't dug into this, but I'm assuming because it's able to re-use the
`clap` compiled as for both `cargo-oudated` and `cargo` in the dep graph
(more on this below). It also seems to have removed some …
=> uses clap for the CLI

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs
This PR just updates the Cargo dependency to `0.58`. Named profiles were stabilized in Rust 1.57, but `cargo outdated` would complain about the feature not being stable due to the older Cargo version it was linked against.
Also, I ran `cargo update` to pull in minor version updates for other deps.
=> Update `cargo` dependency

src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/cli.rs, src/main.rs
Closes #285
If you use `cargo outdated` on a workspace with relative dependencies referring to a package that is external to the workspace, `cargo outdated` will convert to the reference to an absolute path reference. This however fails is the external project (or one of its' dependencies) have a relative dependency back to a package in the workspace, as you now have the same package in two different places (both the temp one and the original one). 
This proposed switch mitigates this problem by skipping all dependencies that are relative and outside the workspace - basically all that would otherwise have been converted into absolute path dependencies.
When elaborating the result, the switch will omit reporting package that have been removed (since they were skipped). Transitive …
=> fix(285): Added switch ignore-external-rel to workaround issue 285

src/cli.rs
I am not sure if this should be considered a breaking change, i.e. if this arg is being used in scripts this way?
=> fix: Typo in `--aggressive` arg

.github/workflows/deploy.yml
To speed up CI jobs that use `cargo-outdated` and avoid running the `cargo install cargo-outdated` command, I think it would be helpful to automatically deploy `cargo-outdated` on `Linux`, `MacOS` and `Windows` through `GithHub Actions`. The action is triggered when a new tag is added and pushed.
I hope this is appreciated, thanks in advance for your review!
=> Deploy cargo-outdated automatically

Cargo.lock, Cargo.toml, src/cli.rs
This updates `clap` to the v3.1.6 derive API. Do note that this will require an MSRV bump up to 1.54.0 since that's the minimum that any of the `clap` v3 versions require.
The updated CLI should match the existing one (all the tests pass :tada:). Here is the old vs new help page for comparison. As you can see things are the same aside from some very small differences like the options being sorted by the short name instead of long, a different default wrap length, and the use of color (can't be seen from just the text of course)
_Old_
```
cargo-outdated 0.11.0
Displays information about project dependency versions
USAGE:
cargo outdated [OPTIONS]
OPTIONS:
-a, --aggresssive                  Ignores channels for latest updates
--color <COLOR>                Output coloring [default: auto] …
```
=> Update clap to v3.1

Cargo.lock, Cargo.toml, src/cargo_ops/temp_project.rs
This should probably be combined with the update to Clap v4 to avoid the duplicate dependency, but this alone should be enough to support local registries using the `sparse+http` protocol.
Closes #347
=> Bump Cargo to 0.71.0 to support sparse+http registries.

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, .typos.toml, CHANGELOG.md, CONTRIBUTING.md, Cargo.lock, Cargo.toml, justfile, rust-toolchain.toml, rustfmt.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/mod.rs, src/cargo_ops/temp_project.rs, src/cli.rs, src/main.rs
Rollup of #348 and #349
Updates `toml` to v0.7
Trims down the CI and uses `just` as the command runner.
=> Metadata and CI update

.github/workflows/lint.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
Also bumps the minor version because we've changed the MSRV in the `Cargo.toml`.
Closes #355
=> Notes MSRV is what is required to _run_

CHANGELOG.md, Cargo.lock, Cargo.toml
After the last few PRs updating deps, this is the final RUSTSEC advisory that remained and was possible to eliminate by bumping `tempfile`'s minor version.
Closes #350
=> Bump tempfile due to RUSTSEC-2023-0018

Cargo.lock, Cargo.toml
Cargo now supports strings for the debug config, but `cargo outdated`
needs to upgrade to support crates using that, or else it errors:
$ cargo outdated
error: failed to parse manifest at `[...]/Cargo.toml`
Caused by:
expected a boolean or an integer
in `profile.dev.debug`
=> Upgrade to cargo 0.72

Cargo.lock, Cargo.toml, src/cargo_ops/mod.rs
`serde`'s macros could be used via `serde` crate as its `derive` feature is enabled.
=> use serde macro via serde crate instead of serde_derive

.github/workflows/lint.yml, Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/mod.rs, src/cargo_ops/temp_project.rs, src/macros.rs, src/main.rs
This updates compatibility with new cargo features, e.g. [version-less manifests](https://github.com/rust-lang/cargo/pull/12786).
The `git2-curl` and `toml` dependencies are also updated to keep up with `cargo`.
The optional `termcolor` dependency is removed, as it is now unused.
=> Upgrade to cargo 0.76.0 (MSRV 1.73)

.github/workflows/lint.yml, Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/pkg_status.rs, src/cargo_ops/temp_project.rs, src/macros.rs, src/main.rs
Resolves #402. Resolves #401. Resolves #384. Resolves #404.
This MR updates all dependencies to their latest versions. The only update that required code changes was the `cargo` crate, which was caused by:
* `cargo::util::Config` being renamed to `cargo::util::context::GlobalContext`.
* `cargo::sources::source::Source::query_vec()` returning a `Vec<IndexSummary>` instead of a `Vec<Summary>`.
=> Update cargo and other dependencies

CHANGELOG.md, Cargo.toml
Once this merges we can release v0.16.0
=> chore: bump version

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs
This replaces few hashmaps to FxHashMaps, reducing instructions count for some workloads about x2. Memory consumption still bad (i mean, that it is currently bad, not that this pr changes this).
=> move to fxhashmap for speed

.github/workflows/lint.yml, Cargo.lock, Cargo.toml
This allows running `cargo-outdated` on Rust 2024 edition crates without setting `cargo-features = ["edition2024"]` in Cargo.toml.
=> Update cargo version
