kbknapp/cargo-outdated

src/lockfile.rs, src/main.rs
This is for #2. If I missed some, let me know, I'll change them and update PR
=> Changed some unwraps to unwrap_or_else

src/deps/raw_dep.rs, src/lockfile.rs, src/main.rs
Checks the exit status of `cargo update` and fixes duplicate dependency entries that were causing it to fail.
=> Various fixes

src/lockfile.rs
=> fix: Set bin.path in the temp manifest

src/cargo_files/dependency_tree.rs
=> fix: print updates for root package

src/main.rs
=> fix: force normal verbosity on error

README.md, src/main.rs
=> imp: enable --all-features by default

src/main.rs
=> fix: no default features unless specified

.travis.yml, Cargo.lock, Cargo.toml, src/macros.rs, src/main.rs
=>  fix: debug build missing `termcolor` dependency

Cargo.lock
=> chore: updates dependencies

src/cargo_ops/temp_project.rs
=> fix: calls `update()` if not default registry

src/cargo_ops/temp_project.rs
=> perf: replaces `format!()` with `Path.join()`

src/cargo_ops/temp_project.rs, src/main.rs
=> fix: replaces relative paths with absolute ones in latest manifests

src/cargo_ops/temp_project.rs
=> fix: optional dependencies are also features

src/cargo_ops/temp_project.rs
Fixes #101 
~~I was actually surprised that there's no official crates.io API client to use out of the box. Checked other tools e.g. `cargo-edit` and they've also built a niche client.~~
This might be related to rust-lang/cargo#4679
=> fix: filter yanked packages out

Cargo.lock, Cargo.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/main.rs
=> imp: use docopt instead of clap

Cargo.lock, Cargo.toml, src/cargo_ops/temp_project.rs, src/main.rs
=> Use tempfile instead of tempdir

src/main.rs
=> Allow nightly cargo features

src/cargo_ops/temp_project.rs
Allow the situation like this: https://github.com/kbknapp/cargo-outdated/issues/167#issuecomment-542312379
Fixes #167
=> Allow aliased dependencies

Cargo.lock, Cargo.toml, README.md, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/main.rs
New PR to see if Travis CI will report the status back unlike #213 :(
=> Cargo v0.43.1 bump

README.md
=> Specify --locked in installation instructions

src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/pkg_status.rs, src/cargo_ops/temp_project.rs, src/main.rs
Just what the title says.
Seems liks `cargo fmt` hasn't run in a while. Maybe it would be worth adding it to ci checks? Or doing it as a pre commit hook, ... ?
=> cargo clippy + fmt

.cargo/config.toml, .github/workflows/rust.yml, rustfmt.toml, src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/pkg_status.rs, src/cargo_ops/temp_project.rs, src/main.rs
This PR adds a lint and clippy check stage in preparation for more CI and more checks before any merges.
=> Adding more CI stages 

Cargo.lock, Cargo.toml
This fixes the build on Alpine edge.
=> Update dependencies for openssl 3.0 support

Cargo.lock, Cargo.toml, src/cargo_ops/temp_project.rs
=> Upgrade cargo to support the 2021 edition

src/cargo_ops/elaborate_workspace.rs, src/cargo_ops/temp_project.rs, src/error.rs, src/main.rs
Making the codebase a little cleaner :)
=> Remove hard unwraps in the code and add an error module

src/main.rs
=> fix: remove non-json line when run in workspace mode.

CHANGELOG.md, Cargo.lock, Cargo.toml
Closes #307
I've included a version bump, let me know if this works for you :)
=> Update cargo to fix libgit2 segfaults (#307)

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs
Hi :)
I noticed that you started upgrading to clapv4 and were nearly done.
Since I've been upgrading clap for a hand full of projects in the last few months, I thought I could help out and resolve the remaining open issues :)
If you want, I can also point this PR to your base `clapv4` branch #340
=> Update to clap v4 continuation

Cargo.lock, Cargo.toml, src/cli.rs
Updates to clap v4 as followup to #312
=> update to clap v4

src/cargo_ops/mod.rs, src/cargo_ops/temp_project.rs
=> Include patch table in manifest

src/cargo_ops/temp_project.rs
As reported in #366 this previously failed with a panic and message "Source should be ready". Now, private registries still cannot be queried but after a timeout (it seems), those dependencies from private registries are just skipped (with a message "Update for xyz cannot be found").
Still needs a proper fix and #366 should be updated (or a new ticket created) to fix the issue with private registries.
=> fix: deal more gracefully with private registries
